---
- name: Create App Dir
  file: state=directory path={{app_base}}/{{version}} mode=0777

- name: Copy Solr Tar
  unarchive: copy=yes src={{mirror}}/solr/{{version}}/solr-{{version}}.tgz dest={{app_base}}/{{version}} mode=0777 copy=no

- name: Updating Configs
  template: src=../roles/solr/templates/solr.in.sh dest={{app_base}}/{{version}}/solr-{{version}}/bin/

- name: Create ZK Chroot
  shell: "{{app_base}}/{{version}}/solr-{{version}}/server/scripts/cloud-scripts/zkcli.sh -zkhost {{zoo}} -cmd makepath /solr-{{version}}"

- name: Add Solr Service Solr
  template: src=../roles/solr/templates/solr dest=/etc/init.d/solr-{{version}} mode=755

- name: Enable Service
  service: name="solr-{{version}}" enabled=yes

- name: Starting Solr
  shell: "{{app_base}}/{{version}}/solr-{{version}}/bin/solr start"

- name: Waiting for Solr to Start
  wait_for: port={{ port }} state=present delay=5 timeout=30

- name: Upload basic config
  shell: "{{app_base}}/{{version}}/solr-{{version}}/server/scripts/cloud-scripts/zkcli.sh -zkhost {{zoo}}/solr-{{version}} -cmd upconfig -confname basic_configs -confdir {{app_base}}/{{version}}/solr-{{version}}/server/solr/configsets/basic_configs/conf/"

- name: Upload data_driven_schema_configs
  shell: "{{app_base}}/{{version}}/solr-{{version}}/server/scripts/cloud-scripts/zkcli.sh -zkhost {{zoo}}/solr-{{version}} -cmd upconfig -confname data_driven_schema_configs -confdir {{app_base}}/{{version}}/solr-{{version}}/server/solr/configsets/data_driven_schema_configs/conf"

- name: Create SolrClient_unittest Collection
  shell: "{{app_base}}/{{version}}/solr-{{version}}/bin/solr create_collection -c SolrClient_unittest -p {{ port }} -shards 2"

- name: Create source_coll Collection
  shell: "{{app_base}}/{{version}}/solr-{{version}}/bin/solr create_collection -c source_coll -d basic_configs -p {{ port }} -shards 2"

- name: Upload source_coll schema
  shell: "{{app_base}}/{{version}}/solr-{{version}}/server/scripts/cloud-scripts/zkcli.sh -zkhost {{zoo}}/solr-{{version}} -cmd upconfig -confname source_coll -confdir {{code_dir}}/test/resources/{{version}}/"

- name: Reload Collection
  shell: curl -XGET 'http://localhost:{{ port }}/solr/admin/cores?action=RELOAD&core=source_coll_shard1_replica1'

- name: Create dest_coll Collection
  shell: "{{app_base}}/{{version}}/solr-{{version}}/bin/solr create_collection -c dest_coll -d basic_configs -p {{ port }} -shards 2"

- name: Upload dest_coll schema
  shell: "{{app_base}}/{{version}}/solr-{{version}}/server/scripts/cloud-scripts/zkcli.sh -zkhost {{zoo}}/solr-{{version}} -cmd upconfig -confname dest_coll -confdir {{code_dir}}/test/resources/{{version}}/"

- name: Reload Collection
  shell: curl -XGET 'http://localhost:{{ port }}/solr/admin/cores?action=RELOAD&core=dest_coll_shard1_replica1'

- name: Startup Service jerry-rig
  lineinfile: dest="/etc/init.d/rc.local" line='{{app_base}}/{{version}}/solr-{{version}}/bin/solr start'
